# -*- coding: utf-8 -*-
"""Langchain-chroma_db- vector Store/database.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tkfIkyfIKId6VCABGCFwg6NcFQE8O34i
"""

!pip install langchain chromadb pypdf langchain-huggingface langchain-community sentence-transformers

!pip install -U `langchain-chroma

from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

from langchain_core.documents import Document

doc1 = Document(
    page_content="""
Virat Kohli is one of the greatest batsmen in modern cricket. He was born on November 5, 1988, in Delhi, India.
He has served as the captain of the Indian national cricket team in all formats.
Kohli is known for his aggressive batting style, consistency, and ability to chase targets successfully.
He has scored more than 25,000 international runs across formats and has numerous centuries in ODIs and Tests.
In the IPL, he has been a loyal player for Royal Challengers Bangalore since 2008.
""",
    metadata={"team": "Royal Challengers Bangalore"}
)

doc2 = Document(
    page_content="""
Rohit Sharma is an elegant right-handed batsman known for his effortless stroke play.
Born on April 30, 1987, he has captained the Indian cricket team in multiple formats.
He holds the record for the highest individual score in ODI cricket (264 runs).
Rohit is famous for scoring three double centuries in One Day Internationals.
In the Indian Premier League, he has led Mumbai Indians to multiple championship titles.
""",
    metadata={"team": "Mumbai Indians"}
)

doc3 = Document(
    page_content="""
MS Dhoni, also known as Captain Cool, is regarded as one of the best finishers in cricket history.
Born on July 7, 1981, in Ranchi, India, he led India to victory in the 2007 T20 World Cup,
2011 ODI World Cup, and 2013 Champions Trophy. Dhoni is known for his calm temperament
and exceptional wicketkeeping skills. He has been the face of Chennai Super Kings in the IPL.
""",
    metadata={"team": "Chennai Super Kings"}
)

doc4 = Document(
    page_content="""
Hardik Pandya is a dynamic all-rounder who contributes with both bat and ball.
Born on October 11, 1993, he is known for his explosive batting in the lower middle order.
He bowls medium pace and can pick crucial wickets.
Pandya has played key roles in India's victories in limited-overs cricket.
In the IPL, he has represented Gujarat Titans as captain.
""",
    metadata={"team": "Gujarat Titans"}
)

doc5 = Document(
    page_content="""
KL Rahul is a technically sound batsman who can play across formats.
Born on April 18, 1992, he has opened the innings in both Tests and limited-overs cricket.
Rahul is known for his adaptability and stylish cover drives.
He has scored centuries in all three formats of international cricket.
In the IPL, he has been associated with Lucknow Super Giants as captain.
""",
    metadata={"team": "Lucknow Super Giants"}
)

doc6 = Document(
    page_content="""
Jasprit Bumrah is one of the most feared fast bowlers in world cricket.
Born on December 6, 1993, he is known for his unique bowling action and deadly yorkers.
Bumrah has consistently delivered match-winning performances in Test and limited-overs cricket.
He has played a vital role in India's overseas Test victories.
In the IPL, he represents Mumbai Indians as a premier fast bowler.
""",
    metadata={"team": "Mumbai Indians"}
)

doc7 = Document(
    page_content="""
Ravindra Jadeja is a versatile all-rounder and one of the best fielders in the world.
Born on December 6, 1988, he contributes with left-arm spin bowling and aggressive batting.
Jadeja has been instrumental in India's Test successes with both bat and ball.
His quick reflexes in the field often change the course of matches.
In the IPL, he is a key player for Chennai Super Kings.
""",
    metadata={"team": "Chennai Super Kings"}
)

doc8 = Document(
    page_content="""
Shubman Gill is a young and talented opening batsman for India.
Born on September 8, 1999, he gained attention after leading India's Under-19 team to victory in 2018.
Gill is known for his elegant stroke play and composure under pressure.
He has scored centuries in international cricket across formats.
In the IPL, he has represented Gujarat Titans.
""",
    metadata={"team": "Gujarat Titans"}
)

doc9 = Document(
    page_content="""
David Warner is an aggressive Australian opening batsman.
Born on October 27, 1986, he is known for his attacking style and consistency in T20 cricket.
Warner has been one of the top run-scorers in IPL history.
He has also captained teams in franchise cricket and led them to title victories.
In the IPL, he has been associated with Delhi Capitals.
""",
    metadata={"team": "Delhi Capitals"}
)

doc10 = Document(
    page_content="""
Andre Russell is a powerful all-rounder from the West Indies.
Born on April 29, 1988, he is known for his explosive batting and fast bowling.
Russell is capable of changing the game within a few overs due to his power-hitting ability.
He has been one of the most impactful players in T20 leagues worldwide.
In the IPL, he plays for Kolkata Knight Riders.
""",
    metadata={"team": "Kolkata Knight Riders"}
)

document = [doc1,doc2,doc3,doc4,doc5,doc6,doc7,doc8,doc9,doc10]

!pip install sentence-transformers

vector_store = Chroma(
    embedding_function=HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2"),
    persist_directory='my_chroma_db_store',
    collection_name='sample_data'
)

#adding documents
vector_store.add_documents(document)

vector_store.get(include=['embeddings','documents','metadatas'])

#search document
vector_store.similarity_search(
    query='Who among these are bowler? ',
    k = 2 # fetch most 2 document
)

#search with similarity_score => minimum means highest similarity
vector_store.similarity_search_with_score(
    query='who among these are bowlers? ',
    k = 2
)

#metadata filtering
vector_store.similarity_search_with_score(
    query= "",
    filter={"team":"Chennai Super Kings"}
)

#updating documents
updated_docs = Document(
    page_content='Virat Kohli is one is one of indian player',
    metadata={"team":"Royal Challengers Bangalore"}
)
vector_store.update_document(document_id='a82c0503-9cf7-4a80-8695-19f89d06ef06',document = updated_docs)

#view documents
vector_store.get(include=['embeddings','documents','metadatas'])

#delete documents
vector_store.delete(ids = ['a82c0503-9cf7-4a80-8695-19f89d06ef06'])

#view documents
vector_store.get(include=['embeddings','documents','metadatas'])

