# -*- coding: utf-8 -*-
"""Langchain-project - Youtube Chatbotipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rBFZt5onHzMoMw238G_lb8RIoRAuvvyC
"""

# import os
# os.environ['HUGGINGFACEHUB_API_TOKEN'] = '****************'

!pip install -q youtube-transcript-api langchain-community langchain-huggingface faiss-cpu python-dotenv sentence-transformers

from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import ChatHuggingFace,HuggingFaceEndpoint,HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import PromptTemplate

#setup for embedding model and chat_model

#step1: embedding model
embedding_model = HuggingFaceEmbeddings(model_name = "sentence-transformers/all-MiniLM-L6-v2")

#step2: chat model
llm = HuggingFaceEndpoint(
    repo_id="openai/gpt-oss-20b",
    task = "text-generation"
)

chat_model = ChatHuggingFace(llm = llm)

"""# step 1 a - Indexing (Document Ingestion)"""

video_id = "7ARBJQn6QkM"  #enter only id , not full url
try:
  #if you don't care which language, this returns the best one , if you don't know exact language then only pass video_id
  transcript_list = YouTubeTranscriptApi().fetch(video_id,languages=['en'])

  #flatten it to plain text
  transcript = " ".join(chunk.text for chunk in transcript_list)

except TranscriptsDisabled:
  print("No Caption available for this video.")

print(transcript)

"""#Step 1b => Indexing (Text Splitting)"""

splitter = RecursiveCharacterTextSplitter(chunk_size=1000,chunk_overlap=200)
chunks = splitter.create_documents([transcript])

print(len(chunks))

"""#Step 1c & 1d => Indexing (Embedding Generation and Storing in Vector Store)"""

vector_store = FAISS.from_documents(chunks,embedding_model)

vector_store.index_to_docstore_id

vector_store.get_by_ids(['4d4a0bc6-0916-40a4-be3b-1400dfc10ae3'])

"""#step 2: Retrieval"""

retriever = vector_store.as_retriever(search_type='similarity',search_kwargs={"k":4})

retriever

retriever.invoke('what is alexnet')

"""#Step 3: Augmentation"""

prompt = PromptTemplate(
    template="""
      You are a helpful assistant.
      Answer only from the provided transcript context.
      If the context is insufficient, just say you don't know.

      {content}\n
      Question: {question}
    """,
    input_variables=['content','question']
)

question = 'what is alexnet'
retrieved_docs = retriever.invoke(question)

context_text = "\n\n".join(doc.page_content for doc in retrieved_docs)

final_prompt = prompt.invoke({"content":context_text,"question":question})

"""#Step 4: Generation"""

answer = chat_model.invoke(final_prompt)
print(answer.content)

"""#Building a chain"""

from langchain_core.runnables import RunnableParallel, RunnablePassthrough,RunnableLambda
from langchain_core.output_parsers import StrOutputParser

def format_docs(retrieved_doc):
  context_text = "\n\n".join(doc.page_content for doc in retrieved_doc)
  return context_text

parallel_chain = RunnableParallel(
    content = retriever | RunnableLambda(format_docs) ,
    question = RunnablePassthrough()
)

parallel_chain.invoke('what is alexnet')

parser = StrOutputParser()
main_chain = parallel_chain | prompt | chat_model | parser

main_chain.invoke("what is alexnet")

